//HintName: TestEnum.g.cs
// <auto-generated>
// This code was generated by EnumGenerator.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace Tests;

internal static class TestEnumUtils
{
	public static IReadOnlyList<Tests.TestClass.TestEnum> Values { get; } = Enum.GetValues<Tests.TestClass.TestEnum>();

	public static string ToStringFast(this Tests.TestClass.TestEnum value)
	{
		return value switch
		{
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}

	public static ReadOnlySpan<byte> AsUtf8Span(this Tests.TestClass.TestEnum value)
	{
		return value switch
		{
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}
}
