//HintName: BlendEquationModeEXT.g.cs
// <auto-generated>
// This code was generated by EnumGenerator.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace Silk.NET.OpenGL;

public static class BlendEquationModeEXTGen
{
	public static IReadOnlyList<Silk.NET.OpenGL.BlendEquationModeEXT> Values { get; } = Enum.GetValues<Silk.NET.OpenGL.BlendEquationModeEXT>();

	public static ReadOnlySpan<byte> NullTerminatedMemberNames => "FuncAdd\0Min\0Max\0FuncSubtract\0FuncReverseSubtract\0AlphaMinSgix\0AlphaMaxSgix\0"u8;

	public static string ToStringFast(this Silk.NET.OpenGL.BlendEquationModeEXT value)
	{
		return value switch
		{
			Silk.NET.OpenGL.BlendEquationModeEXT.FuncAdd => "FuncAdd",
			Silk.NET.OpenGL.BlendEquationModeEXT.Min => "Min",
			Silk.NET.OpenGL.BlendEquationModeEXT.Max => "Max",
			Silk.NET.OpenGL.BlendEquationModeEXT.FuncSubtract => "FuncSubtract",
			Silk.NET.OpenGL.BlendEquationModeEXT.FuncReverseSubtract => "FuncReverseSubtract",
			Silk.NET.OpenGL.BlendEquationModeEXT.AlphaMinSgix => "AlphaMinSgix",
			Silk.NET.OpenGL.BlendEquationModeEXT.AlphaMaxSgix => "AlphaMaxSgix",
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}

	public static ReadOnlySpan<byte> AsUtf8Span(this Silk.NET.OpenGL.BlendEquationModeEXT value)
	{
		return value switch
		{
			Silk.NET.OpenGL.BlendEquationModeEXT.FuncAdd => "FuncAdd"u8,
			Silk.NET.OpenGL.BlendEquationModeEXT.Min => "Min"u8,
			Silk.NET.OpenGL.BlendEquationModeEXT.Max => "Max"u8,
			Silk.NET.OpenGL.BlendEquationModeEXT.FuncSubtract => "FuncSubtract"u8,
			Silk.NET.OpenGL.BlendEquationModeEXT.FuncReverseSubtract => "FuncReverseSubtract"u8,
			Silk.NET.OpenGL.BlendEquationModeEXT.AlphaMinSgix => "AlphaMinSgix"u8,
			Silk.NET.OpenGL.BlendEquationModeEXT.AlphaMaxSgix => "AlphaMaxSgix"u8,
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}

	public static int GetIndex(this Silk.NET.OpenGL.BlendEquationModeEXT value)
	{
		return value switch
		{
			Silk.NET.OpenGL.BlendEquationModeEXT.FuncAdd => 0,
			Silk.NET.OpenGL.BlendEquationModeEXT.Min => 1,
			Silk.NET.OpenGL.BlendEquationModeEXT.Max => 2,
			Silk.NET.OpenGL.BlendEquationModeEXT.FuncSubtract => 3,
			Silk.NET.OpenGL.BlendEquationModeEXT.FuncReverseSubtract => 4,
			Silk.NET.OpenGL.BlendEquationModeEXT.AlphaMinSgix => 5,
			Silk.NET.OpenGL.BlendEquationModeEXT.AlphaMaxSgix => 6,
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}

	public static Silk.NET.OpenGL.BlendEquationModeEXT FromIndex(int index)
	{
		return index switch
		{
			0 => Silk.NET.OpenGL.BlendEquationModeEXT.FuncAdd,
			1 => Silk.NET.OpenGL.BlendEquationModeEXT.Min,
			2 => Silk.NET.OpenGL.BlendEquationModeEXT.Max,
			3 => Silk.NET.OpenGL.BlendEquationModeEXT.FuncSubtract,
			4 => Silk.NET.OpenGL.BlendEquationModeEXT.FuncReverseSubtract,
			5 => Silk.NET.OpenGL.BlendEquationModeEXT.AlphaMinSgix,
			6 => Silk.NET.OpenGL.BlendEquationModeEXT.AlphaMaxSgix,
			_ => throw new ArgumentOutOfRangeException(nameof(index), index, null),
		};
	}
}
