//HintName: TestEnum.g.cs
// <auto-generated>
// This code was generated by EnumGenerator.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;

namespace Tests;

public static partial class TestEnumExtensions
{
	public static string ToStringFast(this TestEnum value)
	{
		return value switch
		{
			TestEnum.None => "None",
			TestEnum.First => "First",
			TestEnum.Second => "Second",
			TestEnum.Third => "Third",
			TestEnum.Fourth => "Fourth",
			TestEnum.Fifth => "Fifth",
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}

	public static ReadOnlySpan<byte> AsUtf8Span(this TestEnum value)
	{
		return value switch
		{
			TestEnum.None => "None"u8,
			TestEnum.First => "First"u8,
			TestEnum.Second => "Second"u8,
			TestEnum.Third => "Third"u8,
			TestEnum.Fourth => "Fourth"u8,
			TestEnum.Fifth => "Fifth"u8,
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}
}

public static partial class TestEnumUtils
{
	public static IReadOnlyList<TestEnum> Values { get; } = Enum.GetValues<TestEnum>();

	public static ReadOnlySpan<byte> NullTerminatedMemberNames => "None\0First\0Second\0Third\0Fourth\0Fifth\0"u8;
}
