//HintName: DateTimeKind.g.cs
// <auto-generated>
// This code was generated by EnumGenerator.
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace System;

public static class DateTimeKindUtils
{
	public static IReadOnlyList<DateTimeKind> Values { get; } = Enum.GetValues<DateTimeKind>();

	public static ReadOnlySpan<byte> NullTerminatedMemberNames => "Unspecified\0Utc\0Local\0"u8;

	public static string ToStringFast(this DateTimeKind value)
	{
		return value switch
		{
			DateTimeKind.Unspecified => "Unspecified",
			DateTimeKind.Utc => "Utc",
			DateTimeKind.Local => "Local",
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}

	public static ReadOnlySpan<byte> AsUtf8Span(this DateTimeKind value)
	{
		return value switch
		{
			DateTimeKind.Unspecified => "Unspecified"u8,
			DateTimeKind.Utc => "Utc"u8,
			DateTimeKind.Local => "Local"u8,
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}
}
