//HintName: DateTimeKind.g.cs
// <auto-generated>
// This code was generated by EnumGenerator.
// </auto-generated>

#nullable enable

using System.Collections.Generic;

namespace System;

public static class DateTimeKindGen
{
	public static IReadOnlyList<System.DateTimeKind> Values { get; } = Enum.GetValues<System.DateTimeKind>();

	public static ReadOnlySpan<byte> NullTerminatedMemberNames => "Unspecified\0Utc\0Local\0"u8;

	public static string ToStringFast(this System.DateTimeKind value)
	{
		return value switch
		{
			System.DateTimeKind.Unspecified => "Unspecified",
			System.DateTimeKind.Utc => "Utc",
			System.DateTimeKind.Local => "Local",
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}

	public static ReadOnlySpan<byte> AsUtf8Span(this System.DateTimeKind value)
	{
		return value switch
		{
			System.DateTimeKind.Unspecified => "Unspecified"u8,
			System.DateTimeKind.Utc => "Utc"u8,
			System.DateTimeKind.Local => "Local"u8,
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}

	public static int GetIndex(this System.DateTimeKind value)
	{
		return value switch
		{
			System.DateTimeKind.Unspecified => 0,
			System.DateTimeKind.Utc => 1,
			System.DateTimeKind.Local => 2,
			_ => throw new ArgumentOutOfRangeException(nameof(value), value, null),
		};
	}

	public static System.DateTimeKind FromIndex(int index)
	{
		return index switch
		{
			0 => System.DateTimeKind.Unspecified,
			1 => System.DateTimeKind.Utc,
			2 => System.DateTimeKind.Local,
			_ => throw new ArgumentOutOfRangeException(nameof(index), index, null),
		};
	}
}
