//HintName: GenerateEnumUtilitiesAttribute.g.cs
// <auto-generated>
// This code was generated by EnumGenerator.
// </auto-generated>

#nullable enable

namespace EnumGenerator;

[global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
internal sealed class GenerateEnumUtilitiesAttribute : global::System.Attribute
{
	public GenerateEnumUtilitiesAttribute()
	{
	}

	public GenerateEnumUtilitiesAttribute(string? generatedClassName)
	{
		GeneratedClassName = generatedClassName;
	}

	public string? GeneratedClassName { get; set; }
}

[global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
internal sealed class GenerateEnumUtilitiesAttribute<T> : global::System.Attribute
	where T : global::System.Enum
{
	public GenerateEnumUtilitiesAttribute()
	{
	}

	public GenerateEnumUtilitiesAttribute(string? generatedClassName)
	{
		GeneratedClassName = generatedClassName;
	}

	public string? GeneratedClassName { get; set; }
}